import type { NextPage } from "next";
import Head from "next/head";

//components
import { ButtonOne, ButtonTwo } from "../components/Buttons";
import Nav from "../components/Nav";
import { HeaderThree, HeaderSix } from "../components/Headings";
import HomeShopItem from "../components/HomeShopItem";
import { HomeShopItemProps } from "../components/HomeShopItem";
import BeforeFooter from "../components/BeforeFooter";
import Footer from "../components/Footer";

const categories: HomeShopItemProps[] = [
  {
    image: "assets/category-headphones/mobile/image-xx99-mark-onee.png",
    imageName: "Headphones",
  },
  {
    image: "assets/category-speakers/mobile/image-zx9.jpg",
    imageName: "Headphones",
  },
  {
    image: "assets/category-headphones/mobile/image-xx99-mark-one.jpg",
    imageName: "Headphones",
  },
];

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>

      <main>
        <header className="flex flex-col h-screen bg-center bg-contain bg-header-mobile md:bg-header-tablet lg:bg-header-desktop text-white">
          <Nav />

          <div className="flex flex-col flex-grow justify-center items-center px-4">
            <HeaderSix>NEW PRODUCT</HeaderSix>
            <HeaderThree>
              XX99 MARK II <br /> HEADPHONES
            </HeaderThree>
            <p className="text-center py-6">
              Experience natural, lifelike audio and exceptional build quality
              made for the passionate music enthusiast.
            </p>
            <ButtonOne text="SEE PRODUCT" extraStyle="py-5 font-bold" />
          </div>
        </header>
        <section className="py-20 px-6">
          {categories.map(({ image, imageName }, index) => (
            <HomeShopItem key={index} image={image} imageName={imageName} />
          ))}
        </section>
        <section className="bg-primary rounded-md px-6 mx-4 flex flex-col justify-center items-center zx9">
          <img
            src="./assets/home/mobile/image-speaker-zx9.png"
            alt="zx9-speaker"
            className="zx9-img"
          />
          <div className="flex flex-col items-center text-center pt-8">
            <HeaderThree extraStyle="text-white">
              zx9 <br /> speaker
            </HeaderThree>
            <p className="text-white py-6">
              Upgrade to premium speakers that are phenomenally built to deliver
              truly remarkable sound.
            </p>
            <ButtonTwo text="SEE PRODUCT" extraStyle="bg-black w-48 py-3" />
          </div>
        </section>
        <section className="mx-4 rounded-md my-6 bg-zx7-speaker h-80 bg-center bg-cover">
          <div className="h-full flex flex-col justify-center ml-6">
            <HeaderThree extraStyle="!font-semibold mb-12">
              ZX7-speaker
            </HeaderThree>
            <ButtonTwo
              text="see product"
              extraStyle="w-48 text-center uppercase py-2"
              inverted
            />
          </div>
        </section>
        <section className="flex flex-col lg:flex-row mx-4 bg-white rounded-md">
          <img
            src="assets/home/mobile/image-earphones-yx1.jpg"
            className="w-full"
          />
          <div className="my-8 px-6 mt-4 bg-gray py-8">
            <HeaderThree extraStyle="font-semibold mb-12">
              YX1 EARPHONES
            </HeaderThree>
            <ButtonTwo
              text="see product"
              extraStyle="w-48 text-center uppercase py-2"
              inverted
            />
          </div>
        </section>
        <BeforeFooter />
      </main>

      <Footer />
      <style jsx>{`
        .zx9 {
          height: 600px;
        }
        .zx9-img {
          width: 170px;
        }
      `}</style>
    </div>
  );
};

export default Home;
