import type { NextPage } from "next";
import Head from "next/head";
import styled from "styled-components";
//components
import { ButtonOne } from "../components/Buttons";
import { Nav } from "../components/Nav";
import {
  HeaderOne,
  HeaderTwo,
  HeaderThree,
  HeaderFour,
  HeaderFive,
  HeaderSix,
} from "../components/Headings";
//assets
//  "header-mobile": "url('')",
//         "header-mobile": "url('')",

// const Header = styled.header`
//   height: 100vh;

//   color: #fff;
// `;

// background: url() 1440px,
//     url(/assets/home/tablet/image-header.jpg) 1440px, url() 750px;

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>

      <main>
        <header className="flex flex-col h-screen bg-center bg-cover bg-header-mobile md:bg-header-tablet lg:bg-header-desktop text-white">
          <Nav />

          <div className="flex flex-col h-full justify-center items-center px-4">
            <HeaderSix>NEW PRODUCT</HeaderSix>
            <HeaderThree>
              XX99 MARK II <br /> HEADPHONES
            </HeaderThree>
            <p className="text-center py-6">
              Experience natural, lifelike audio and exceptional build quality
              made for the passionate music enthusiast.
            </p>
            <ButtonOne text="SEE PRODUCT" extraStyle="py-2" />
          </div>
        </header>
      </main>

      <footer className=""></footer>
    </div>
  );
};

export default Home;
